// The wire contract of DESIGN.md §6: "gRPC is the service. Anything else is a
// gateway in front of it."
//
// Three shapes in here are not stylistic choices, and each one is a reason
// gRPC was picked over HTTP:
//
//   - Review is bidirectional because a person working a queue wants their
//     decisions to take effect on work still running. Over HTTP that is polling
//     plus a submit endpoint, which is the same thing with latency and more
//     state on both sides.
//   - WatchJob is server-streaming because progress on a minutes-long job is a
//     stream, and SSE is a stream pretending to be a response.
//   - UploadSource is client-streaming because a corpus is not a field in a
//     message, and §8.4 spools the received bytes to disk: a 10GB dump read
//     into a string is a service that dies on the first real customer.
//
// The enums mirror pkg/alchemy's closed sets deliberately. Those sets are
// closed because a consumer switching on the field must not silently fall
// through, and an open wire enum would reopen what the Go contract closed.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.1
// source: alchemy/v1/alchemy.proto

package alchemyv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Alchemy_CreateJob_FullMethodName      = "/alchemy.v1.Alchemy/CreateJob"
	Alchemy_GetJob_FullMethodName         = "/alchemy.v1.Alchemy/GetJob"
	Alchemy_GetResult_FullMethodName      = "/alchemy.v1.Alchemy/GetResult"
	Alchemy_StreamResult_FullMethodName   = "/alchemy.v1.Alchemy/StreamResult"
	Alchemy_DeleteJob_FullMethodName      = "/alchemy.v1.Alchemy/DeleteJob"
	Alchemy_UploadSource_FullMethodName   = "/alchemy.v1.Alchemy/UploadSource"
	Alchemy_WatchJob_FullMethodName       = "/alchemy.v1.Alchemy/WatchJob"
	Alchemy_Review_FullMethodName         = "/alchemy.v1.Alchemy/Review"
	Alchemy_ListFindings_FullMethodName   = "/alchemy.v1.Alchemy/ListFindings"
	Alchemy_Decide_FullMethodName         = "/alchemy.v1.Alchemy/Decide"
	Alchemy_ExtendOntology_FullMethodName = "/alchemy.v1.Alchemy/ExtendOntology"
	Alchemy_Assert_FullMethodName         = "/alchemy.v1.Alchemy/Assert"
)

// AlchemyClient is the client API for Alchemy service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The google.api.http options below are §6's last paragraph: a REST/JSON
// gateway generated from these same definitions, "a translation, never a
// second source of truth about what the service does". They are on the RPCs
// rather than in a side-car mapping file because a second document describing
// the same service drifts, and an annotation that cannot compile without its
// method cannot. One RPC is deliberately unannotated; see Review.
type AlchemyClient interface {
	// Unary for things that are one question.
	CreateJob(ctx context.Context, in *CreateJobRequest, opts ...grpc.CallOption) (*Job, error)
	GetJob(ctx context.Context, in *GetJobRequest, opts ...grpc.CallOption) (*Job, error)
	GetResult(ctx context.Context, in *GetResultRequest, opts ...grpc.CallOption) (*Result, error)
	// A large result is not one message; see §8.4. gRPC's default limit is 4MB
	// and a large import blows through it, so GetResult refuses a result that
	// does not fit rather than truncating one, and points here.
	//
	// Over HTTP the refusal is kept even though HTTP has no such limit: a
	// gateway that quietly served what gRPC refused would be the second source
	// of truth. A custom verb rather than a query parameter because a flag that
	// changes the shape of a response is two routes pretending to be one.
	StreamResult(ctx context.Context, in *GetResultRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ResultPage], error)
	DeleteJob(ctx context.Context, in *DeleteJobRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Upload is client-streaming: a corpus is not a field in a message.
	//
	// body:"*" is the only mapping a client stream allows, and it makes the
	// request body a sequence of SourceChunk messages rather than one — which is
	// what keeps §8.4 true over HTTP too: a frame is decoded and forwarded at a
	// time, so a 10GB dump is never a 10GB buffer. The path takes no parameters
	// because a client-streaming method cannot bind them; the first frame names
	// the source, exactly as it does over gRPC.
	UploadSource(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[SourceChunk, Source], error)
	// Progress is server-streaming: stages, counts, and conflicts as they are
	// found rather than at the end.
	//
	// Over HTTP this is newline-delimited JSON, and Server-Sent Events when the
	// caller asks for them by Accept. Same events, same order. §6 called SSE "a
	// stream pretending to be a response" and that is still true; it is offered
	// because EventSource is all a browser has, and §6's own reason for a
	// gateway is that browsers exist.
	WatchJob(ctx context.Context, in *WatchJobRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[JobEvent], error)
	// Review is bidirectional: items out, decisions in, on one connection, so a
	// decision reaches an extraction that has not run yet.
	//
	// It carries no google.api.http option, and the absence is the decision
	// rather than an oversight. A bidirectional stream has no honest translation
	// into a request and a response: a reviewer must answer item three while item
	// four is still arriving, and an HTTP/1.1 body must be finished before its
	// response is read. grpc-gateway will generate a bidi handler if asked, and
	// it deadlocks or degrades into the polling-plus-submit shape §6 rejected —
	// and a route that looks like it works is worse than none, because the first
	// person to find out is a buyer with a queue of real decisions in it. So the
	// gateway answers this path 501, naming the gRPC method, and the OpenAPI
	// document says the same. Refusing is a translation of "this cannot be
	// translated"; pretending is not.
	Review(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ReviewDecision, ReviewItem], error)
	// ListFindings and Decide are review for a job that has already stopped, and
	// they are the reason the paragraph above is about mid-run review rather
	// than about review.
	//
	// What Review's bidirectional shape buys is that a decision reaches an
	// extraction that has not run yet. That property is real and it is
	// untranslatable: a reviewer answers item three while item four is still
	// arriving, and an HTTP request body must be finished before its response is
	// read. So Review stays unannotated and the gateway still answers its path
	// 501.
	//
	// A job sitting at NEEDS_REVIEW is not that situation. Nothing is running.
	// There is no item four. The findings are a finite list in a finished result
	// and the decisions are a batch, so a list and a batch is not a degradation
	// of the stream — it is what that case actually is, and forcing it through a
	// bidirectional connection was making every HTTP client pay for a property
	// this case does not have. The consequence until now was that a buyer could
	// curl the graph and could not curl "this edge is wrong".
	//
	// The two shapes are one mechanism: a decision submitted here is the same
	// ReviewDecision, applied by the same code, and lands in the same
	// provenance. What differs is when it may be sent.
	ListFindings(ctx context.Context, in *ListFindingsRequest, opts ...grpc.CallOption) (*Findings, error)
	Decide(ctx context.Context, in *DecideRequest, opts ...grpc.CallOption) (*DecideResponse, error)
	// Assert records a fact somebody knows and no document states.
	//
	// It is not a hole in §4. Nothing is stored that a job does not already
	// store, the graph comes back as JSON, and where it goes afterwards is the
	// caller's business exactly as it is for every other result. What it removes
	// is a detour: until now the only way in was to write the fact into a file,
	// upload it, create a job, poll it and fetch the result — five steps and an
	// invented document for one triple — and it arrived stamped
	// PRODUCER_GRAPH_IMPORT, "an existing graph already asserted it", which is
	// not what happened and cost the record the one thing that made it worth
	// admitting: a person who can be asked.
	//
	// It is synchronous, and that is not an optimisation. An assertion has no
	// chunking, no model call and no embedding; it is a parse and a check
	// against the ontology. There is nothing to poll, and returning a job id for
	// a caller to poll would be inventing asynchrony an operation does not have.
	// The Result carries the job id in its `job` field, so the record is still
	// traceable through GetJob like any other.
	//
	// The ontology is optional and checked when given, which is the rule graph
	// sources already follow. An assertion under an ontology that does not
	// declare its types comes back with violations naming them, rather than a
	// refusal: §5 makes the graph never more permissive than the vocabulary, and
	// a person asserting a type nobody declared is exactly the case that has to
	// be visible instead of quietly accepted.
	// ExtendOntology declares accepted proposals in a vocabulary and hands back
	// the next document.
	//
	// It takes a document and returns one, holding nothing between calls,
	// because §4 means the service keeps no ontology: the caller supplies one
	// per job and keeps whatever comes back. That is not a database this design
	// is missing — it is what lets a vocabulary be a file somebody reviews,
	// versions, diffs and can roll back, rather than a row somebody changed.
	//
	// The id always changes. An ontology that gained a type is a different
	// vocabulary and Provenance.ontology names it on every record; two different
	// vocabularies under one id leave a reader unable to say what a graph was
	// checked against, which is the whole of what that field is for.
	//
	// A relation proposal whose ends were never observed is refused rather than
	// declared open, because an undeclared end reads as "any" — a rule widened
	// silently at the moment somebody pressed Accept. The route past it is an
	// order and not a flag: accept the entity types, run again, and the ends are
	// there.
	ExtendOntology(ctx context.Context, in *ExtendOntologyRequest, opts ...grpc.CallOption) (*ExtendOntologyResponse, error)
	Assert(ctx context.Context, in *AssertRequest, opts ...grpc.CallOption) (*Result, error)
}

type alchemyClient struct {
	cc grpc.ClientConnInterface
}

func NewAlchemyClient(cc grpc.ClientConnInterface) AlchemyClient {
	return &alchemyClient{cc}
}

func (c *alchemyClient) CreateJob(ctx context.Context, in *CreateJobRequest, opts ...grpc.CallOption) (*Job, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Job)
	err := c.cc.Invoke(ctx, Alchemy_CreateJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alchemyClient) GetJob(ctx context.Context, in *GetJobRequest, opts ...grpc.CallOption) (*Job, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Job)
	err := c.cc.Invoke(ctx, Alchemy_GetJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alchemyClient) GetResult(ctx context.Context, in *GetResultRequest, opts ...grpc.CallOption) (*Result, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Result)
	err := c.cc.Invoke(ctx, Alchemy_GetResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alchemyClient) StreamResult(ctx context.Context, in *GetResultRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ResultPage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Alchemy_ServiceDesc.Streams[0], Alchemy_StreamResult_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetResultRequest, ResultPage]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Alchemy_StreamResultClient = grpc.ServerStreamingClient[ResultPage]

func (c *alchemyClient) DeleteJob(ctx context.Context, in *DeleteJobRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Alchemy_DeleteJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alchemyClient) UploadSource(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[SourceChunk, Source], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Alchemy_ServiceDesc.Streams[1], Alchemy_UploadSource_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SourceChunk, Source]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Alchemy_UploadSourceClient = grpc.ClientStreamingClient[SourceChunk, Source]

func (c *alchemyClient) WatchJob(ctx context.Context, in *WatchJobRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[JobEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Alchemy_ServiceDesc.Streams[2], Alchemy_WatchJob_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchJobRequest, JobEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Alchemy_WatchJobClient = grpc.ServerStreamingClient[JobEvent]

func (c *alchemyClient) Review(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ReviewDecision, ReviewItem], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Alchemy_ServiceDesc.Streams[3], Alchemy_Review_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ReviewDecision, ReviewItem]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Alchemy_ReviewClient = grpc.BidiStreamingClient[ReviewDecision, ReviewItem]

func (c *alchemyClient) ListFindings(ctx context.Context, in *ListFindingsRequest, opts ...grpc.CallOption) (*Findings, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Findings)
	err := c.cc.Invoke(ctx, Alchemy_ListFindings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alchemyClient) Decide(ctx context.Context, in *DecideRequest, opts ...grpc.CallOption) (*DecideResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DecideResponse)
	err := c.cc.Invoke(ctx, Alchemy_Decide_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alchemyClient) ExtendOntology(ctx context.Context, in *ExtendOntologyRequest, opts ...grpc.CallOption) (*ExtendOntologyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExtendOntologyResponse)
	err := c.cc.Invoke(ctx, Alchemy_ExtendOntology_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alchemyClient) Assert(ctx context.Context, in *AssertRequest, opts ...grpc.CallOption) (*Result, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Result)
	err := c.cc.Invoke(ctx, Alchemy_Assert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AlchemyServer is the server API for Alchemy service.
// All implementations must embed UnimplementedAlchemyServer
// for forward compatibility.
//
// The google.api.http options below are §6's last paragraph: a REST/JSON
// gateway generated from these same definitions, "a translation, never a
// second source of truth about what the service does". They are on the RPCs
// rather than in a side-car mapping file because a second document describing
// the same service drifts, and an annotation that cannot compile without its
// method cannot. One RPC is deliberately unannotated; see Review.
type AlchemyServer interface {
	// Unary for things that are one question.
	CreateJob(context.Context, *CreateJobRequest) (*Job, error)
	GetJob(context.Context, *GetJobRequest) (*Job, error)
	GetResult(context.Context, *GetResultRequest) (*Result, error)
	// A large result is not one message; see §8.4. gRPC's default limit is 4MB
	// and a large import blows through it, so GetResult refuses a result that
	// does not fit rather than truncating one, and points here.
	//
	// Over HTTP the refusal is kept even though HTTP has no such limit: a
	// gateway that quietly served what gRPC refused would be the second source
	// of truth. A custom verb rather than a query parameter because a flag that
	// changes the shape of a response is two routes pretending to be one.
	StreamResult(*GetResultRequest, grpc.ServerStreamingServer[ResultPage]) error
	DeleteJob(context.Context, *DeleteJobRequest) (*emptypb.Empty, error)
	// Upload is client-streaming: a corpus is not a field in a message.
	//
	// body:"*" is the only mapping a client stream allows, and it makes the
	// request body a sequence of SourceChunk messages rather than one — which is
	// what keeps §8.4 true over HTTP too: a frame is decoded and forwarded at a
	// time, so a 10GB dump is never a 10GB buffer. The path takes no parameters
	// because a client-streaming method cannot bind them; the first frame names
	// the source, exactly as it does over gRPC.
	UploadSource(grpc.ClientStreamingServer[SourceChunk, Source]) error
	// Progress is server-streaming: stages, counts, and conflicts as they are
	// found rather than at the end.
	//
	// Over HTTP this is newline-delimited JSON, and Server-Sent Events when the
	// caller asks for them by Accept. Same events, same order. §6 called SSE "a
	// stream pretending to be a response" and that is still true; it is offered
	// because EventSource is all a browser has, and §6's own reason for a
	// gateway is that browsers exist.
	WatchJob(*WatchJobRequest, grpc.ServerStreamingServer[JobEvent]) error
	// Review is bidirectional: items out, decisions in, on one connection, so a
	// decision reaches an extraction that has not run yet.
	//
	// It carries no google.api.http option, and the absence is the decision
	// rather than an oversight. A bidirectional stream has no honest translation
	// into a request and a response: a reviewer must answer item three while item
	// four is still arriving, and an HTTP/1.1 body must be finished before its
	// response is read. grpc-gateway will generate a bidi handler if asked, and
	// it deadlocks or degrades into the polling-plus-submit shape §6 rejected —
	// and a route that looks like it works is worse than none, because the first
	// person to find out is a buyer with a queue of real decisions in it. So the
	// gateway answers this path 501, naming the gRPC method, and the OpenAPI
	// document says the same. Refusing is a translation of "this cannot be
	// translated"; pretending is not.
	Review(grpc.BidiStreamingServer[ReviewDecision, ReviewItem]) error
	// ListFindings and Decide are review for a job that has already stopped, and
	// they are the reason the paragraph above is about mid-run review rather
	// than about review.
	//
	// What Review's bidirectional shape buys is that a decision reaches an
	// extraction that has not run yet. That property is real and it is
	// untranslatable: a reviewer answers item three while item four is still
	// arriving, and an HTTP request body must be finished before its response is
	// read. So Review stays unannotated and the gateway still answers its path
	// 501.
	//
	// A job sitting at NEEDS_REVIEW is not that situation. Nothing is running.
	// There is no item four. The findings are a finite list in a finished result
	// and the decisions are a batch, so a list and a batch is not a degradation
	// of the stream — it is what that case actually is, and forcing it through a
	// bidirectional connection was making every HTTP client pay for a property
	// this case does not have. The consequence until now was that a buyer could
	// curl the graph and could not curl "this edge is wrong".
	//
	// The two shapes are one mechanism: a decision submitted here is the same
	// ReviewDecision, applied by the same code, and lands in the same
	// provenance. What differs is when it may be sent.
	ListFindings(context.Context, *ListFindingsRequest) (*Findings, error)
	Decide(context.Context, *DecideRequest) (*DecideResponse, error)
	// Assert records a fact somebody knows and no document states.
	//
	// It is not a hole in §4. Nothing is stored that a job does not already
	// store, the graph comes back as JSON, and where it goes afterwards is the
	// caller's business exactly as it is for every other result. What it removes
	// is a detour: until now the only way in was to write the fact into a file,
	// upload it, create a job, poll it and fetch the result — five steps and an
	// invented document for one triple — and it arrived stamped
	// PRODUCER_GRAPH_IMPORT, "an existing graph already asserted it", which is
	// not what happened and cost the record the one thing that made it worth
	// admitting: a person who can be asked.
	//
	// It is synchronous, and that is not an optimisation. An assertion has no
	// chunking, no model call and no embedding; it is a parse and a check
	// against the ontology. There is nothing to poll, and returning a job id for
	// a caller to poll would be inventing asynchrony an operation does not have.
	// The Result carries the job id in its `job` field, so the record is still
	// traceable through GetJob like any other.
	//
	// The ontology is optional and checked when given, which is the rule graph
	// sources already follow. An assertion under an ontology that does not
	// declare its types comes back with violations naming them, rather than a
	// refusal: §5 makes the graph never more permissive than the vocabulary, and
	// a person asserting a type nobody declared is exactly the case that has to
	// be visible instead of quietly accepted.
	// ExtendOntology declares accepted proposals in a vocabulary and hands back
	// the next document.
	//
	// It takes a document and returns one, holding nothing between calls,
	// because §4 means the service keeps no ontology: the caller supplies one
	// per job and keeps whatever comes back. That is not a database this design
	// is missing — it is what lets a vocabulary be a file somebody reviews,
	// versions, diffs and can roll back, rather than a row somebody changed.
	//
	// The id always changes. An ontology that gained a type is a different
	// vocabulary and Provenance.ontology names it on every record; two different
	// vocabularies under one id leave a reader unable to say what a graph was
	// checked against, which is the whole of what that field is for.
	//
	// A relation proposal whose ends were never observed is refused rather than
	// declared open, because an undeclared end reads as "any" — a rule widened
	// silently at the moment somebody pressed Accept. The route past it is an
	// order and not a flag: accept the entity types, run again, and the ends are
	// there.
	ExtendOntology(context.Context, *ExtendOntologyRequest) (*ExtendOntologyResponse, error)
	Assert(context.Context, *AssertRequest) (*Result, error)
	mustEmbedUnimplementedAlchemyServer()
}

// UnimplementedAlchemyServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAlchemyServer struct{}

func (UnimplementedAlchemyServer) CreateJob(context.Context, *CreateJobRequest) (*Job, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateJob not implemented")
}
func (UnimplementedAlchemyServer) GetJob(context.Context, *GetJobRequest) (*Job, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetJob not implemented")
}
func (UnimplementedAlchemyServer) GetResult(context.Context, *GetResultRequest) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetResult not implemented")
}
func (UnimplementedAlchemyServer) StreamResult(*GetResultRequest, grpc.ServerStreamingServer[ResultPage]) error {
	return status.Errorf(codes.Unimplemented, "method StreamResult not implemented")
}
func (UnimplementedAlchemyServer) DeleteJob(context.Context, *DeleteJobRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteJob not implemented")
}
func (UnimplementedAlchemyServer) UploadSource(grpc.ClientStreamingServer[SourceChunk, Source]) error {
	return status.Errorf(codes.Unimplemented, "method UploadSource not implemented")
}
func (UnimplementedAlchemyServer) WatchJob(*WatchJobRequest, grpc.ServerStreamingServer[JobEvent]) error {
	return status.Errorf(codes.Unimplemented, "method WatchJob not implemented")
}
func (UnimplementedAlchemyServer) Review(grpc.BidiStreamingServer[ReviewDecision, ReviewItem]) error {
	return status.Errorf(codes.Unimplemented, "method Review not implemented")
}
func (UnimplementedAlchemyServer) ListFindings(context.Context, *ListFindingsRequest) (*Findings, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListFindings not implemented")
}
func (UnimplementedAlchemyServer) Decide(context.Context, *DecideRequest) (*DecideResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Decide not implemented")
}
func (UnimplementedAlchemyServer) ExtendOntology(context.Context, *ExtendOntologyRequest) (*ExtendOntologyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExtendOntology not implemented")
}
func (UnimplementedAlchemyServer) Assert(context.Context, *AssertRequest) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Assert not implemented")
}
func (UnimplementedAlchemyServer) mustEmbedUnimplementedAlchemyServer() {}
func (UnimplementedAlchemyServer) testEmbeddedByValue()                 {}

// UnsafeAlchemyServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AlchemyServer will
// result in compilation errors.
type UnsafeAlchemyServer interface {
	mustEmbedUnimplementedAlchemyServer()
}

func RegisterAlchemyServer(s grpc.ServiceRegistrar, srv AlchemyServer) {
	// If the following call pancis, it indicates UnimplementedAlchemyServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Alchemy_ServiceDesc, srv)
}

func _Alchemy_CreateJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlchemyServer).CreateJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Alchemy_CreateJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlchemyServer).CreateJob(ctx, req.(*CreateJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Alchemy_GetJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlchemyServer).GetJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Alchemy_GetJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlchemyServer).GetJob(ctx, req.(*GetJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Alchemy_GetResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlchemyServer).GetResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Alchemy_GetResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlchemyServer).GetResult(ctx, req.(*GetResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Alchemy_StreamResult_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetResultRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AlchemyServer).StreamResult(m, &grpc.GenericServerStream[GetResultRequest, ResultPage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Alchemy_StreamResultServer = grpc.ServerStreamingServer[ResultPage]

func _Alchemy_DeleteJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlchemyServer).DeleteJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Alchemy_DeleteJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlchemyServer).DeleteJob(ctx, req.(*DeleteJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Alchemy_UploadSource_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AlchemyServer).UploadSource(&grpc.GenericServerStream[SourceChunk, Source]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Alchemy_UploadSourceServer = grpc.ClientStreamingServer[SourceChunk, Source]

func _Alchemy_WatchJob_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchJobRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AlchemyServer).WatchJob(m, &grpc.GenericServerStream[WatchJobRequest, JobEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Alchemy_WatchJobServer = grpc.ServerStreamingServer[JobEvent]

func _Alchemy_Review_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AlchemyServer).Review(&grpc.GenericServerStream[ReviewDecision, ReviewItem]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Alchemy_ReviewServer = grpc.BidiStreamingServer[ReviewDecision, ReviewItem]

func _Alchemy_ListFindings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFindingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlchemyServer).ListFindings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Alchemy_ListFindings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlchemyServer).ListFindings(ctx, req.(*ListFindingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Alchemy_Decide_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecideRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlchemyServer).Decide(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Alchemy_Decide_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlchemyServer).Decide(ctx, req.(*DecideRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Alchemy_ExtendOntology_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExtendOntologyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlchemyServer).ExtendOntology(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Alchemy_ExtendOntology_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlchemyServer).ExtendOntology(ctx, req.(*ExtendOntologyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Alchemy_Assert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlchemyServer).Assert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Alchemy_Assert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlchemyServer).Assert(ctx, req.(*AssertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Alchemy_ServiceDesc is the grpc.ServiceDesc for Alchemy service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Alchemy_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "alchemy.v1.Alchemy",
	HandlerType: (*AlchemyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateJob",
			Handler:    _Alchemy_CreateJob_Handler,
		},
		{
			MethodName: "GetJob",
			Handler:    _Alchemy_GetJob_Handler,
		},
		{
			MethodName: "GetResult",
			Handler:    _Alchemy_GetResult_Handler,
		},
		{
			MethodName: "DeleteJob",
			Handler:    _Alchemy_DeleteJob_Handler,
		},
		{
			MethodName: "ListFindings",
			Handler:    _Alchemy_ListFindings_Handler,
		},
		{
			MethodName: "Decide",
			Handler:    _Alchemy_Decide_Handler,
		},
		{
			MethodName: "ExtendOntology",
			Handler:    _Alchemy_ExtendOntology_Handler,
		},
		{
			MethodName: "Assert",
			Handler:    _Alchemy_Assert_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamResult",
			Handler:       _Alchemy_StreamResult_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "UploadSource",
			Handler:       _Alchemy_UploadSource_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "WatchJob",
			Handler:       _Alchemy_WatchJob_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Review",
			Handler:       _Alchemy_Review_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "alchemy/v1/alchemy.proto",
}
